import type { DashboardTransactionRow } from '@liqvia2/shared';

/** Realistic UK construction company transactions for demo mode. */
export const DEMO_RECENT_TXN: DashboardTransactionRow[] = [
  {
    id: 'demo-txn-1',
    direction: 'IN',
    description: 'Milestone payment — Riverside Apartments Phase 2',
    category: 'customer',
    transactionDate: '2024-06-05',
    amount: 185_000,
    status: 'cleared',
  },
  {
    id: 'demo-txn-2',
    direction: 'OUT',
    description: 'Weekly payroll — site crew & office staff',
    category: 'payroll',
    transactionDate: '2024-06-04',
    amount: 42_300,
    status: 'cleared',
  },
  {
    id: 'demo-txn-3',
    direction: 'OUT',
    description: 'Steel frame supplier — BuildRight Ltd',
    category: 'supplier',
    transactionDate: '2024-06-03',
    amount: 78_500,
    status: 'cleared',
  },
  {
    id: 'demo-txn-4',
    direction: 'IN',
    description: 'Retention release — Oakwood Office Fit-out',
    category: 'customer',
    transactionDate: '2024-06-01',
    amount: 34_000,
    status: 'cleared',
  },
  {
    id: 'demo-txn-5',
    direction: 'OUT',
    description: 'CIS/PAYE monthly remittance — HMRC',
    category: 'tax',
    transactionDate: '2024-05-31',
    amount: 28_750,
    status: 'cleared',
  },
  {
    id: 'demo-txn-6',
    direction: 'OUT',
    description: 'Plant hire — excavator & crane weekly',
    category: 'supplier',
    transactionDate: '2024-05-30',
    amount: 12_400,
    status: 'cleared',
  },
  {
    id: 'demo-txn-7',
    direction: 'IN',
    description: 'Progress claim #4 — Greenfield School Extension',
    category: 'customer',
    transactionDate: '2024-05-28',
    amount: 96_000,
    status: 'cleared',
  },
  {
    id: 'demo-txn-8',
    direction: 'OUT',
    description: 'Term loan repayment — Barclays Commercial',
    category: 'loan',
    transactionDate: '2024-05-27',
    amount: 15_000,
    status: 'cleared',
  },
  {
    id: 'demo-txn-9',
    direction: 'OUT',
    description: 'Concrete pour — Hanson UK batch delivery',
    category: 'supplier',
    transactionDate: '2024-05-24',
    amount: 31_200,
    status: 'cleared',
  },
  {
    id: 'demo-txn-10',
    direction: 'IN',
    description: 'Variation order payment — City Council car park',
    category: 'customer',
    transactionDate: '2024-05-22',
    amount: 47_500,
    status: 'cleared',
  },
];
